### PR TITLE
chore: lint tests

### PR DESCRIPTION
**Pull request by faddat**
## Description

An earlier PR did not actually lint tests.  This PR actually ensures that test code is linted and consistent. The first PR had two things masking the linting of test files and I'd only disabled one.

----

Closes #XXX

**All** items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow-up issues.

PR review checkboxes:

I have...

- [x]  Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x]  Targeted PR against the correct branch
- [x]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to the GitHub issue with discussion and accepted design
- [ ]  Targets only one GitHub issue
- [ ]  Wrote unit and integration tests
- [ ]  Wrote relevant migration scripts if necessary
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)
- [ ]  Updated the scripts for local run, e.g genesis_config_commands.sh if the PR changes parameters
- [ ]  Add an issue in the [e2e-tests repo](https://github.com/dymensionxyz/e2e-tests) if necessary

SDK Checklist
- [ ] Import/Export Genesis
- [ ] Registered Invariants
- [ ] Registered Events
- [ ] Updated openapi.yaml
- [ ] No usage of go `map`
- [ ] No usage of `time.Now()`
- [ ] Used fixed point arithmetic and not float arithmetic
- [ ] Avoid panicking in Begin/End block as much as possible
- [ ] No unexpected math Overflow
- [ ] Used `sendCoin` and not `SendCoins`
- [ ] Out-of-block compute is bounded
- [ ] No serialized ID at the end of store keys
- [ ] UInt to byte conversion should use BigEndian

Full security checklist [here](https://www.faulttolerant.xyz/2024-01-16-cosmos-security-1/)

----;

For Reviewer:

- [ ]  Confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  Confirmed all author checklist items have been addressed

---;

After reviewer approval:

- [ ]  In case the PR targets the main branch, PR should not be squash merge in order to keep meaningful git history.
- [ ]  In case the PR targets a release branch, PR must be rebased.

### CODE REVIEW

**Comment by omritoptix** [comment]
@faddat linter is still failing

**Comment by faddat** [comment]
@omritoptix - indeed, I'm having a proper "works on my computer" situation rn

**Review by mtsitrin — DISMISSED** [review]

**Comment by faddat** [comment]
@mtsitrin please hang on a moment before merging this.  

* https://github.com/dymensionxyz/dymension/actions/runs/8327179536/job/22784308756?pr=685#step:5:263

**Comment by faddat** [comment]
theory: in the tests there's a double registered proto.  When I added error checks, this gave it a chance to give output.  Theory could be wrong. 

https://github.com/dymensionxyz/dymension/actions/runs/8327179536/job/22784308756?pr=685#step:5:32

**Comment by faddat** [comment]
Ah, luckily, it seems to have resolved :).

**Review by omritoptix — APPROVED** [review]

**Review by omritoptix — APPROVED** [review]

**Pull request merged**
