### PR TITLE
fix: upgrade cometbft

### PR DESCRIPTION
**Pull request by faddat**
## Description

This was originally a part of dymensionxyz/dymension#677, but failed to integrate smoothly with dymension, so it's been broken out into its own PR so that it can be worked on separately from other version bumps.

----

Closes #XXX

**All** items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow-up issues.

PR review checkboxes:

I have...

- [x]  Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [x]  Targeted PR against the correct branch
- [x]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to the GitHub issue with discussion and accepted design
- [ ]  Targets only one GitHub issue
- [ ]  Wrote unit and integration tests
- [ ]  Wrote relevant migration scripts if necessary
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)
- [ ]  Updated the scripts for local run, e.g genesis_config_commands.sh if the PR changes parameters
- [ ]  Add an issue in the [e2e-tests repo](https://github.com/dymensionxyz/e2e-tests) if necessary

SDK Checklist
- [ ] Import/Export Genesis
- [ ] Registered Invariants
- [ ] Registered Events
- [ ] Updated openapi.yaml
- [ ] No usage of go `map`
- [ ] No usage of `time.Now()`
- [ ] Used fixed point arithmetic and not float arithmetic
- [ ] Avoid panicking in Begin/End block as much as possible
- [ ] No unexpected math Overflow
- [ ] Used `sendCoin` and not `SendCoins`
- [ ] Out-of-block compute is bounded
- [ ] No serialized ID at the end of store keys
- [ ] UInt to byte conversion should use BigEndian

Full security checklist [here](https://www.faulttolerant.xyz/2024-01-16-cosmos-security-1/)

----;

For Reviewer:

- [ ]  Confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  Confirmed all author checklist items have been addressed

---;

After reviewer approval:

- [ ]  In case the PR targets the main branch, PR should not be squash merge in order to keep meaningful git history.
- [ ]  In case the PR targets a release branch, PR must be rebased.

### CODE REVIEW

**Comment by omritoptix** [comment]
@faddat merge from main will prob fix linter issue

**Review by omritoptix — DISMISSED** [review]

**Review by mtsitrin — APPROVED** [review]

**Comment by omritoptix** [comment]
@faddat can you please fix conflicts?

**Review by danwt — APPROVED** [review]
tests fail

**Comment by faddat** [comment]
@danwt you're referring to the e2e tests, correct?

I opened #688 to address :)

**Comment by danwt** [comment]
yes @faddat thanks!

**Review by danwt — DISMISSED** [review]

**Comment by danwt** [comment]
Hey @faddat it looks like the tests only fail on this PR and not others, which points to a problem with the upgrades.

I tried to upgrade comet myself https://github.com/dymensionxyz/dymension/pull/722 and got some build error. How did you get around that?

**Comment by faddat** [comment]
Basically the reason I'd promote this change is that there are ongoing fixes to cometbft.  I can try to make a PR to the e2e test repo that would resolve this.

**Comment by faddat** [comment]
Here's a PR to the e2e tests:

* https://github.com/dymensionxyz/e2e-tests/pull/75

**Comment by faddat** [comment]
I'm going to temporarily update this PR to use a replace statement, to demonstrate functionality.

**Pull request closed without merging**
