### PR TITLE
fix   proto update opt in status response

### LINKED ISSUE #1627: x/sequencer proto update opt in status, need to use response
```
  rpc UpdateOptInStatus (MsgUpdateOptInStatus) returns (MsgUpdateOptInStatus);

message MsgUpdateOptInStatus {
  option (cosmos.msg.v1.signer) = "creator";
  // creator is the bech32-encoded address of the sequencer account which is the account that the message was sent from.
  string creator = 1;
  // OptedIn : the new value
  bool opted_in = 2;
}

message MsgUpdateOptInStatusResponse {}
  ```

wrong return type

GPT found it lol

### PR DESCRIPTION
**Pull request by DSHIVAAY-23**
closes #1627

### CODE REVIEW

**Comment by mtsitrin** [comment]
@DSHIVAAY-23 you should run `make proto-gen` after the update and update the `.go` files

**Comment by DSHIVAAY-23** [comment]
> @DSHIVAAY-23 you should run `make proto-gen` after the update and update the `.go` files

**Comment by DSHIVAAY-23** [comment]
> @DSHIVAAY-23 you should run `make proto-gen` after the update and update the `.go` files

should i make a new commit or just ammend on it?

**Comment by mtsitrin** [comment]
@DSHIVAAY-23 pls generate the `.go` file (`make proto-gen`) in new commit

**Comment by DSHIVAAY-23** [comment]
> make proto-gen

cp: can't stat 'github.com/dymensionxyz/dymension/v*/*': No such file or directory
make: *** [Makefile:178: proto-gen] Error 1
getting this error while running this command

**Comment by danwt** [comment]
Might need to pull dependencies first

**Pull request closed without merging**
